#!bash
# vim:set ft=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :

# uname -s = Darwin = macos

# (macports) prioritize gnu utils over bsd utils
for f in /opt/local/bin /opt/local/libexec/gnubin /opt/local/sbin
do
  if [ -d "$f" ]
  then
    export PATH="$f:$PATH"
  fi
done

