#!bash
# vim:set ft=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :

# stty erase ^h

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
