#!bash
# vim:set ft=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :



#----------- DIRS -----------

function d () {
  echo # to visually separate from prompt, which likely also includes the current path
  dirs -v
  echo # to visually separate from prompt, which likely also includes the current path
  }

function pd () {
  if [ $# -eq 0 ]
  then
    pushd >/dev/null || return
  fi
  local d
  for d in "$@"
  do
    if [ -z "$d" ]
    then
      # treat '' as lack of an argument instead of just complaining
      pushd >/dev/null || return
    else
      pushd "$d" >/dev/null || return
    fi
  done
  d
  }
function pd- () {
  pd -1
  }

# DIRS is a shell+perl script
alias diirs='DIRS'  # or 'dirs -v' in a pinch
alias dirss='DIRS'  # or 'dirs -v' in a pinch

function PUSHD () {
  pushd "$@" >/dev/null
  echo
  diirs
  }

function POPD () {
  popd "$@" >/dev/null
  echo
  diirs
  }

function UP () {
  local n=1
  if [ -n "$1" ]
  then
    n="$1" ; shift
  fi
  PUSHD +$n
  }

function DOWN () {
  local n=1
  if [ -n "$1" ]
  then
    n="$1" ; shift
  fi
  n=$(( n - 1 ))
  PUSHD -$n
  }
alias Down=DOWN
