#!bash
# vim:set ft=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :

function gi ()
{
  local one="$1" ; shift
  case "$one" in
    (tpush) git push "$@" ;;
    (tpull) git pull "$@" ;;
    (tco) git checkout "$@" ;;
  esac
}

function gnew ()
{ # create a new local+remote branch
  # Usage: gnew branch_name
  local name="$*"
  # There's only one valid argument, so combine all args.
  # To please github, name will have colons and whitespace replaced with hyphen.
  # For other special characters and restrictions, you're on your own and good luck.
  # https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
  name="$(sed -E 's,[:[:space:]]+,-,g' <<<"$name")"
  git checkout -b "$name"
  git push -u origin "$name"
}

