#!bash
# vim:set ft=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :


#----------- Linux -----------
alias keys='loadkeys ~/.keymap.$(uname -s)'
# example: fuser /usr/bin/xterm 2>&1 |fupid
alias fupid="sed -e 's/^.*://;s/[^0-9 ]//g'"
