#!bash
# vim:set ft=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :




# for use when a machine is repurposed behind our back
alias SSH='ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias SCP='scp -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias ssh_=SSH
alias scp_=SCP
alias _ssh=SSH
alias _scp=SCP
