#!bash
# vim:set ft=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :
#!zsh skip if zsh

[[ -n $ZSH_VERSION ]] && return


# enable bash programmable completion features
for f in \
  /etc/bash_completion \
  /etc/bash_completion.d \
  /usr/share/bash-completion/bash_completion \
  /usr/local/etc/bash_completion.d \
; do
  if [ -r "$f" ]
  then
    for g in $( find "$f" -type f -o -type l )
    do
      case "$g" in
        (/etc/bash_completion.d/000_bash_completion_compat.bash) ;;
        (*) . "$g" ;;
      esac
    done
  fi
done

unset f g
