#!bash
# vim:set ft=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :

#
# app-specific configs
#

export VISUAL=vi
export EDITOR="$VISUAL"

export PAGER='less -FRXi'
export BAT_PAGER='less -FRXi'

export PGPPATH="$HOME"/mail/.pgppath


# Set in basic bashrc instead of here.
# PARINIT='rTbgqR B=.?_A_a Q=_s>|'
# export PARINIT


# make less more friendly for non-text input files, see lesspipe(1)
if type -P lesspipe >/dev/null 2>&1
then
  eval "$(SHELL=/bin/sh lesspipe)"
fi

for f in $( find "$HOME"/usr/bin/ -name '*.completion' )
do
  # (use find to avoid dancing around bash's unfortunate nullglob behavior; "shopt -s nullglob" should be the default)
  . "$f"
done

if [ $(which git |wc -l) -ge 1 ]
then
  if [ ! -e "$bash_RC_public"/git-flow-completion.bash ]
  then
    (cd "$bash_RC_public" && . git-flow-completion.bash.README )
  fi
  if [ -r "$bash_RC_public"/git-flow-completion.bash ]
  then
    . "$bash_RC_public"/git-flow-completion.bash
  fi
fi

if [ -d /etc/salt/. ]
then
  if [ ! -e "$bash_RC_public"/salt_bash_completion ]
  then
    (cd "$bash_RC_public" && . salt_bash_completion.README )
  fi
  if [ -r "$bash_RC_public"/salt_bash_completion ]
  then
    . "$bash_RC_public"/salt_bash_completion
  fi
fi

for f in /usr/share/doc/tmux/examples/bash_completion_tmux.sh
do
  if [ -f "$f" ]
  then
    . "$f"
  fi
done



if type -P ispell >/dev/null 2>&1
then
  export ISPELL="$(type -P ispell)"
elif [ -n "$HOMEBREW_PREFIX" ] && [ -x "$HOMEBREW_PREFIX"/bin/ispell ]
then
  export ISPELL="$HOMEBREW_PREFIX"/bin/ispell
elif [ -x /usr/local/bin/ispell ]
then
  export ISPELL=/usr/local/bin/ispell
elif [ -x /usr/bin/ispell ]
then
  export ISPELL=/usr/bin/ispell
fi


# grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
export GREP_OPTIONS='--exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn'
# GREP="$(type -P grep)"
# alias grep="$GREP $GREP_OPTIONS"
# unset GREP
alias grep="command grep $GREP_OPTIONS"
unset GREP_OPTIONS
