# vim:set ft=sh:

#
# symlink this file as ~/.bashrc
#





# some systems default to 002 or 000, or even stranger
umask 022



# make sure hostname is set and is the hostname, not the fqdn.
# it's a stupid-common rookie mistake.
if [ -z "$HOSTNAME" -o "${HOSTNAME%.*}" != "$HOSTNAME" ]
then
	HOSTNAME="${HOSTNAME:-$(hostname)}"
	# HOSTNAME="$(hostname)"
	HOSTNAME="${HOSTNAME%%.*}"
	export HOSTNAME
fi



# yeah, java :(
if [ -d /usr/lib/jvm/java-6-sun ]
then
	JAVA_HOME=/usr/lib/jvm/java-6-sun
	export JAVA_HOME
	JDK_HOME="${JAVA_HOME}"
	export JDK_HOME
	PATH="${JAVA_HOME}/bin:${PATH}"
	export PATH
fi


# App setup needed even for non-interactive shells.
# (Claws is run from a non-interactive shell.)

PARINIT='rTbgqR B=.?_A_a Q=_s>|'
export PARINIT


#
# belabor the path
#

# path for snap apps
if [ -d /snap/bin ]
then
	PATH="/snap/bin:${PATH}"
fi

# setup for golang: GOPATH and PATH
if [ -z "$GOPATH" ]
then
	if [ -d "$HOME/golang" ]
	then
		GOPATH="$HOME/golang"
	elif [ -d "$HOME/go" ]
	then
		GOPATH="$HOME/go"
	fi
	export GOPATH
fi
if [ -n "$GOPATH" ]
then
	PATH="${GOPATH}/bin:${PATH}"
fi

# my own stuff comes first
PATH="${HOME}/usr/bin:${PATH}"
PATH="${HOME}/bin:${PATH}"
PATH=".:${PATH}"

export PATH


#
#
#

if [ -z "$PS1" ] # non-interactive, so we're done here
then
	return
fi



#
#
#

# From here on is for making interactive sessions bearable.

# from here, assumes bash.  not sh.  not ksh.  not ash.  not zsh.

RC_public="$HOME/.rc-public"
RC_private="$HOME/.rc-private"
bash_RC_public="$RC_public/bashrc.d"
bash_RC_private="$RC_private/bashrc.d"
# or derive from this you must have it relocatable:
#	"$(readlink -f "${BASH_SOURCE[0]}" )"


. "$bash_RC_private"/keys
. "$bash_RC_private"/jobs

# (macports) prioritize gnu utils over bsd utils
for f in /opt/local/bin /opt/local/libexec/gnubin /opt/local/sbin
do
	if [ -d /opt/local/bin ]
	then
		export PATH="$f:$PATH"
	fi
done



if [ "${-/i/}" = "$-" ]	# i is not present in shell options, so is non-interactive
then
	PATH="$HOME/usr/bin:$PATH"
	export PATH
	return
fi






#
# put interactive parts below here
#




. "$bash_RC_public"/interactive
