#!bash
# vim:set ft=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :

#
# symlink this file as ~/.bashrc
#





# some systems default to 002 or 000, or even stranger
umask 022



# make sure hostname is set and is the hostname, not the fqdn.
# it's a stupid-common rookie mistake.
if [ -z "$HOSTNAME" -o "${HOSTNAME%.*}" != "$HOSTNAME" ]
then
  HOSTNAME="${HOSTNAME:-$(hostname)}"
  # HOSTNAME="$(hostname)"
  HOSTNAME="${HOSTNAME%%.*}"
  export HOSTNAME
fi



# yeah, java :(
if [ -d /usr/lib/jvm/java-6-sun ]
then
  JAVA_HOME=/usr/lib/jvm/java-6-sun
  export JAVA_HOME
  JDK_HOME="${JAVA_HOME}"
  export JDK_HOME
  PATH="${JAVA_HOME}/bin:${PATH}"
  export PATH
fi


# App setup needed even for non-interactive shells.
# (Claws is run from a non-interactive shell.)

PARINIT='rTbgqR B=.?_A_a Q=_s>|'
export PARINIT


#
# belabor the path
#

# path for snap apps
if [ -d /snap/bin ]
then
  PATH="/snap/bin:${PATH}"
fi

# setup for golang: GOPATH and PATH
if [ -z "$GOPATH" ]
then
  if [ -d "$HOME/golang" ]
  then
    GOPATH="$HOME/golang"
  elif [ -d "$HOME/go" ]
  then
    GOPATH="$HOME/go"
  fi
  export GOPATH
fi
if [ -n "$GOPATH" ]
then
  PATH="${GOPATH}/bin:${PATH}"
fi

# my own stuff comes first
PATH="${HOME}/usr/bin:${PATH}"
PATH="${HOME}/bin:${PATH}"
PATH=".:${PATH}"

export PATH


# for wlroots/sway manual install
LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu/
export LD_LIBRARY_PATH


#
#
#

if [ -z "$PS1" ] # non-interactive, so we're done here
then
  return
fi



#
#
#

# From here on is for making interactive sessions bearable.

# from here, assumes bash.  not sh.  not ksh.  not ash.  not zsh.


if [ "${-/i/}" = "$-" ] # i is not present in shell options, so is non-interactive
then
  return # non-interactive, so we're done here
fi

RC_public="$HOME/.rc-public"
RC_private="$HOME/.rc-private"
bash_RC_public="$RC_public/bashrc.d"
bash_RC_private="$RC_private/bashrc.d"
# or derive from this you must have it relocatable:
#  "$(readlink -f "${BASH_SOURCE[0]}" )"


if [ -d "$HOME"/.oh-my-bash ] && [ -f "$RC_public"/oh-my-bash.rc ]
then
  # To enable oh-my-bash, do this:
  #    git clone git://github.com/ohmybash/oh-my-bash.git ~/.oh-my-bash

  # For more info on oh-my-bash, see:
  #    https://ohmybash.nntoan.com/
  #    https://ohmybash.github.io/
  #    https://github.com/ohmybash/oh-my-bash
  . "$RC_public"/oh-my-bash.rc
fi


. "$bash_RC_public"/00_fn
. "$bash_RC_public"/00_PROMPT_COMMAND
. "$bash_RC_public"/00_colors
. "$bash_RC_public"/git
. "$bash_RC_private"/keys
. "$bash_RC_private"/jobs
. "$bash_RC_private"/kubectl
. "$bash_RC_private"/terraform
. "$bash_RC_private"/brew

# (macports) prioritize gnu utils over bsd utils
for f in /opt/local/bin /opt/local/libexec/gnubin /opt/local/sbin
do
  if [ -d "$f" ]
  then
    export PATH="$f:$PATH"
  fi
done







#
# put interactive parts below here
#




. "$bash_RC_public"/interactive
