#!bash
# vim:set ft=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :


# See https://brew.sh/ for macos
# and https://docs.brew.sh/Homebrew-on-Linux for linux.

# You might also want to set your HOMEBREW_GITHUB_API_TOKEN.
# https://stackoverflow.com/questions/20130681/setting-github-api-token-for-homebrew
# https://gist.github.com/willgarcia/7347306870779bfa664e


type -P brew >/dev/null && return   # don't bother if brew is already set up

known_breweries=()
known_breweries+=( "${HOME}"/.linuxbrew/bin/brew )
known_breweries+=( "${HOME}"/.homebrew/bin/brew )
known_breweries+=( /home/linuxbrew/.linuxbrew/bin/brew )
known_breweries+=( /opt/homebrew/bin/brew )
known_breweries+=( /usr/local/bin/brew )

for f in "${known_breweries[@]}"
do
  if [ -x "$f" ]
  then
    eval "$("$f" shellenv)"
    break
  fi
done

unset known_breweries


# list of brew gnubins safe to add to PATH
#
# This is my list; your mileage may vary.  Please offer
# a pull request if you think I should change this list
# for all who use this repository.
#
# Adding these to your path will make it so you don't
# have to use names like `gfind` and `ggrep` to run
# GNU versions of `find` and `grep`.
# Don't do this blindly, to avoid interfering with xcode.
gnubin_whitelist=()
gnubin_whitelist+=( coreutils )   # basic stuff like readlink, date, and df
gnubin_whitelist+=( ed )
gnubin_whitelist+=( findutils )
gnubin_whitelist+=( gawk )
gnubin_whitelist+=( gnu-indent )
gnubin_whitelist+=( gnu-sed )
gnubin_whitelist+=( gnu-tar )
gnubin_whitelist+=( gnu-which )
gnubin_whitelist+=( grep )
gnubin_whitelist+=( gsed )
# gnubin_whitelist+=( libtool )
# gnubin_whitelist+=( make )

for f in "${gnubin_whitelist[@]}"
do
  p="${HOMEBREW_PREFIX}/opt/$f"
  g="$p/libexec/gnubin"
  if [ -e "$g" ]
  then
    export PATH="$g:$PATH"
  fi
  g="$p/libexec/gnuman"
  if [ -e "$g" ]
  then
    export MANPATH="$g:${MANPATH+:$MANPATH}"
  fi
  g="$p/share/info"
  if [ -e "$g" ]
  then
    export INFOPATH="$g:${INFOPATH+:$INFOPATH}"
  fi
done

unset gnubin_whitelist


# list of brew bins that must be added manually to PATH,
# ie is keg-only.  This is often because the package
# has conflicts with another package.  An example is
# mysql-client vs mysql.
keg_whitelist=()
keg_whitelist+=( mysql-client )

for f in "${keg_whitelist[@]}"
do
  p="${HOMEBREW_PREFIX}/opt/$f"
  g="$p/bin"
  if [ -e "$g" ]
  then
    export PATH="$g:$PATH"
  fi
  g="$p/share/main"
  if [ -e "$g" ]
  then
    export MANPATH="$g:${MANPATH+:$MANPATH}"
  fi
  g="$p/share/info"
  if [ -e "$g" ]
  then
    export INFOPATH="$g:${INFOPATH+:$INFOPATH}"
  fi
done

unset keg_whitelist

unset f p g

# `brew shellenv` does something like this:
# export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
# export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
# export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
# export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}";
# export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
# export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}";
