#!bash
# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :

# see:
#  https://github.com/pyenv/pyenv
#  https://github.com/pyenv/pyenv-virtualenv

# install:
#  git clone https://github.com/pyenv/pyenv.git ~/.pyenv
#  cd ~/.pyenv && ./src/configure && make -C src
# getting started:
#  pyenv versions
#  pyenv install --list
#  pyenv install --list |grep '^[[:space:]]*[[:digit:]]' | sort -V
#  pyenv install "$( pyenv install --list |grep '^[[:space:]]*[[:digit:]]' | sort -V |grep -v '[^0-9. ]' |tail -1 | sed -E 's/[[:space:]]//g ; s/[.][0-9]+$//' )"
#  pyenv global "$( pyenv versions |grep -v system |sed -E 's/^[*]?[[:space:]]*// ; s/[[:space:]]+.*$//' |grep -v '[^0-9. ]' |tail -1 |sed -E 's/[.][0-9]+$//' )"
#  pip3 install --upgrade pip wheel setuptools

# You may need to install some libraries to get newer pythons to install.
# There should be an error message to help you, but here's a hint:
# sudo apt install libbz2-dev libncurses-dev libreadline-dev libssl-dev libsqlite3-dev
# brew install pyenv bzip2 zlib

if [ -x "$HOME/.pyenv/bin/pyenv" ]
then

  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)" # adds shims to PATH
  if [ "${-/i/}" != "$-" ] # i is present in shell options, so is interactive
  then
    # enables shell completion and the pyenv rehash and shell subcommands
    eval "$(pyenv init -)"
  fi

  # If the virtualenv plugin is installed, enable it.
  #  https://github.com/pyenv/pyenv-virtualenv
  #  git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
  if [ -d "${PYENV_ROOT}/plugins/pyenv-virtualenv/shims" ]
  then
    eval "$(pyenv virtualenv-init -)"
    export PYENV_VIRTUALENV_DISABLE_PROMPT=1
  fi

fi
