#!bash
# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :

# see:
#  https://github.com/pyenv/pyenv
#  https://github.com/pyenv/pyenv-virtualenv

#  git clone https://github.com/pyenv/pyenv.git ~/.pyenv
#  cd ~/.pyenv && src/configure && make -C src

if [ -x "$HOME/.pyenv/bin/pyenv" ]
then

  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)" # adds shims to PATH
  if [ "${-/i/}" != "$-" ] # i is present in shell options, so is interactive
  then
    # enables shell completion and the pyenv rehash and shell subcommands
    eval "$(pyenv init -)"
  fi

  # If the virtualenv plugin is installed, enable it.
  if [ -d "${PYENV_ROOT}/plugins/pyenv-virtualenv/shims" ]
  then
    eval "$(pyenv virtualenv-init -)"
    export PYENV_VIRTUALENV_DISABLE_PROMPT=1
  fi

fi
