#!bash
# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :

# lazy load startup-heavy utilities - defers initialization until first use
# idea from https://dev.to/nickytonline/how-i-used-claude-code-to-speed-up-my-shell-startup-by-95-m0f


# see:
#  https://github.com/pyenv/pyenv
#  https://github.com/pyenv/pyenv-virtualenv

# install pyenv:
#  git clone https://github.com/pyenv/pyenv.git ~/.pyenv
#  cd ~/.pyenv && ./src/configure && make -C src
#  git clone https://github.com/pyenv/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
#  source THIS_FILE
#
# install the latest python:
#  pyenv versions
#  pyenv install --list | tail
#  pyenv install --list | grep '^[[:space:]]*[[:digit:]]' | sort -V | tail
#  py_latest_stable="$( pyenv install --list |grep '^[[:space:]]*[[:digit:]]' | sort -V |grep -v '[^0-9. ]' |tail -1 | sed -E 's/[[:space:]]//g' )"
#  py_major_latest_stable="$( sed -E 's/[.][0-9]+$//' <<<"$py_latest_stable")"
#  echo "py_latest_stable=$py_latest_stable  /  py_major_latest_stable=$py_major_latest_stable"
#  pyenv install "$py_latest_stable"
#  pyenv global "$py_latest_stable"
#  hash -r
#  pip3 install --upgrade pip wheel setuptools

# You may need to install some libraries to get newer pythons to install.
# There should be an error message to help you, but here's some hints:
# * sudo apt install libbz2-dev libncurses-dev libreadline-dev libssl-dev libsqlite3-dev
# * brew install pyenv bzip2 zlib
# * For centos7, this should be helpful:
#   https://github.com/pyenv/pyenv/issues/2416#issuecomment-1326064266

pyenv_loader ()
{
  if [[ $( type -t pyenv ) != file ]] && [ -x "$HOME/.pyenv/bin/pyenv" ]
  then
    unset -f pyenv

    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)" # adds shims to PATH
    if [ "${-/i/}" != "$-" ] # i is present in shell options, so is interactive
    then
      # enables shell completion and the pyenv rehash and shell subcommands
      eval "$(pyenv init -)"
    fi

    # If the virtualenv plugin is installed, enable it.
    #  https://github.com/pyenv/pyenv-virtualenv
    #  git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
    if [ -d "${PYENV_ROOT}/plugins/pyenv-virtualenv/shims" ]
    then
      eval "$(pyenv virtualenv-init -)"
      export PYENV_VIRTUALENV_DISABLE_PROMPT=1
    fi
  fi

}

if [[ $( type -t pyenv ) != file ]]
then
  pyenv () { unset -f pyenv ; pyenv_loader ; pyenv "$@" ; }
fi
