#!bash
# vim:set ft=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent copyindent :

# de-duplicates PATH entries
export PATH="$( dedupPath "$PATH" )"

# and removes current directory from PATH
export PATH="${PATH#.:}"
export PATH="${PATH%:.}"
export PATH="${PATH#:}"
export PATH="${PATH%:}"
export PATH="${PATH/::/:}"
